# Generated by Django 5.0.6 on 2024-05-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('status', models.CharField(max_length=255, verbose_name='Должность')),
                ('image', models.ImageField(upload_to='team/', verbose_name='Фотография сотрудника')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('instagram', models.URLField(verbose_name='instagram')),
                ('facebook', models.URLField(verbose_name='facebook')),
                ('telegram', models.URLField(verbose_name='telegram')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
